name: Nightly Cypress Tests

on:
  workflow_dispatch: # Allow manual triggering
  schedule:
    - cron: "0 1 * * 0" # Run every Sunday at 1:00 AM UTC

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Cypress run
        uses: cypress-io/github-action@v6

      - name: Merge Mochawesome reports
        run: npx mochawesome-merge cypress/results/*.json > cypress/results/mochawesome.json

      - name: Generate HTML report
        run: npx marge cypress/results/mochawesome.json -f mochawesome -o cypress/results

      - name: Generate Test Summary
        id: generate-summary
        run: |
          node get-summary.js cypress/results/mochawesome.json

      - name: Check for summary file  # Add this step back
        uses: dorny/paths-filter@v2
        id: filter
        with:
          filters: |
            summary:
              - 'cypress_summary.env'

      - name: Load summary environment
        run: |
          if [[ ${{ steps.filter.outputs.summary }} == 'true' ]]; then
            echo "CYPRESS_SUMMARY=$(cat cypress_summary.env)" >> $GITHUB_ENV
          else
            echo "CYPRESS_SUMMARY=No summary found" >> $GITHUB_ENV 
          fi

      - name: Upload screenshots
        uses: actions/upload-artifact@v4
        if: failure()
        with:
          name: cypress-screenshots
          path: cypress/screenshots

      - name: Upload videos
        uses: actions/upload-artifact@v4
        with:
          name: cypress-videos
          path: cypress/videos

      - name: Upload test report
        uses: actions/upload-artifact@v3
        with:
          name: cypress-report
          path: cypress/results/mochawesome.html

      - name: Send email notification
        uses: dawidd6/action-send-mail@v3
        if: always()
        with:
          server_address: smtp.gmail.com
          server_port: 587
          username: ${{ secrets.SMTP_USERNAME }}
          password: ${{ secrets.SMTP_PASSWORD }}
          subject: Cypress Nightly Test Results
          to: ${{ secrets.RECIPIENT_EMAIL }}
          from: Cypress Tests <cypress-tests@example.com>
          body: |
            Cypress nightly tests have completed. 

            Workflow run: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}

            ${{ env.CYPRESS_SUMMARY }}  # Include the summary

            See the attached artifacts for details.